In [34]:
import pandas as pd
import plotly.express as px

In [35]:
dados_empacotado = pd.read_excel('../Empacotado.xlsx')
dados_produzido = pd.read_csv('../dados_ordem.csv')

In [36]:
dados_empacotado = dados_empacotado.rename(columns={'Corrida':'Ordem de prod'})

In [51]:
dados_empacotado.head()

,Data Wheaton Dia,Data Wheaton Mês,Data Wheaton Ano,Ordem de prod,Processo Plan,Maquina,Secao,Item,Coluna1,Prefixo,Qtd Empacotado,Qtd Disponivel,Velocidade Plan,Velocidade Real,(Qtd Empacotado/(Qtd Quebra+Qtd Empacotado))
0,13.0,6.0,2024.0,193882,DUPLA GOTA,B1,8,C1268.0000.R001,MB -1344-N1X | F | NH | C | LISO | FLORATTA | ...,MB -1344-N1X,131280,131600,7313,7810,0.828788
1,12.0,6.0,2024.0,193882,DUPLA GOTA,B1,8,C1268.0000.R001,MB -1344-N1X | F | NH | C | LISO | FLORATTA | ...,MB -1344-N1X,127440,128800,7210,7700,0.804545
2,11.0,6.0,2024.0,193882,DUPLA GOTA,B1,8,C1268.0000.R001,MB -1344-N1X | F | NH | C | LISO | FLORATTA | ...,MB -1344-N1X,121040,112000,6901,7370,0.764141
3,1.0,5.0,2024.0,193694,DUPLA GOTA,B1,8,C0529.0000.R001,MB -1390-N1 | F | NH | B | LISO | SOPHIE | NH ...,MB -1390-N1,116712,115200,7416,7488,0.779327
4,14.0,6.0,2024.0,193882,DUPLA GOTA,B1,8,C1268.0000.R001,MB -1344-N1X | F | NH | C | LISO | FLORATTA | ...,MB -1344-N1X,116080,114800,6695,7150,0.732828

In [38]:
dados_produzido.head()

,Ordem de prod,Ref. do Artigo,Duração da ordem,Temperatura (F°),Peso médio (g),Comprimento médio (mm),Diâmetro (mm),Área da gota (mm),Gotas cortadas (toneladas),Total de Frascos,...,Lascado em produção,Dobra,Trinca por choque térmico,Racho na costura,Racho na terminação,Cava no ombro,Ombro mal cheio,Ombro deformado,Martelado,Aderido
0,192970,C0516.0000R,9,2125.51,169.91,125.51,30.97,3887.0447,178.79,1056298,...,12,77,176,0,28,53,68,54,6,2
1,193112,C1164.0000R,3,2173.68,168.17,88.73,38.57,3422.3161,44.73,266234,...,2,35,22,0,9,0,0,0,0,0
2,193164,C1280.0000R,12,2119.41,147.47,100.12,35.43,3547.2516,236.13,1606760,...,33,43,129,1,220,5,0,0,1,2
3,193206,C1284.0000R,4,2170.66,171.15,90.40,36.88,3333.9520,74.31,433696,...,10,26,6,0,65,1,0,1,0,0
4,193207,C1298.0000R,10,2139.29,170.87,98.23,36.56,3591.2888,136.92,801258,...,45,27,87,0,79,0,0,0,0,0

### Agrupando total de empacotados por ordem

In [39]:
empacotado_por_ordem = dados_empacotado.groupby('Ordem de prod')['Qtd Empacotado'].sum()

### Combinando dataframes

In [40]:
df_producao = dados_produzido.merge(empacotado_por_ordem, on='Ordem de prod')

In [41]:
df_producao

,Ordem de prod,Ref. do Artigo,Duração da ordem,Temperatura (F°),Peso médio (g),Comprimento médio (mm),Diâmetro (mm),Área da gota (mm),Gotas cortadas (toneladas),Total de Frascos,...,Dobra,Trinca por choque térmico,Racho na costura,Racho na terminação,Cava no ombro,Ombro mal cheio,Ombro deformado,Martelado,Aderido,Qtd Empacotado
0,192970,C0516.0000R,9,2125.51,169.91,125.51,30.97,3887.0447,178.79,1056298,...,77,176,0,28,53,68,54,6,2,384300
1,193112,C1164.0000R,3,2173.68,168.17,88.73,38.57,3422.3161,44.73,266234,...,35,22,0,9,0,0,0,0,0,207900
2,193164,C1280.0000R,12,2119.41,147.47,100.12,35.43,3547.2516,236.13,1606760,...,43,129,1,220,5,0,0,1,2,1029000
3,193206,C1284.0000R,4,2170.66,171.15,90.40,36.88,3333.9520,74.31,433696,...,26,6,0,65,1,0,1,0,0,181440
4,193207,C1298.0000R,10,2139.29,170.87,98.23,36.56,3591.2888,136.92,801258,...,27,87,0,79,0,0,0,0,0,406080
5,193208,C0104.0000R,2,2176.32,122.10,61.00,27.45,1674.4500,19.74,161700,...,4,17,0,3,0,0,0,0,2,104500
6,193209,C0509.0000R,7,2131.82,191.36,44.37,12.19,540.8703,121.81,638540,...,130,92,2,30,0,2,0,39,0,194250
7,193342,C0516.0000R,20,2125.33,169.96,114.87,33.44,3841.2528,408.76,2409182,...,123,506,0,122,61,92,11,24,8,1459500
8,193368,C1137.0000R,7,2158.78,171.59,77.51,33.83,2622.1633,147.66,861898,...,13,28,0,146,0,0,0,0,0,627200
9,193459,C0068.0000R,3,2148.19,190.83,96.67,37.57,3631.8919,37.59,194712,...,6,31,0,13,0,0,0,0,0,86400
10,193462,C1284.0000R,5,2168.48,172.44,86.08,40.20,3460.4160,90.98,527382,...,7,206,0,121,0,0,0,0,1,262080
11,193463,C1298.0000R,8,2179.18,172.20,93.64,38.75,3628.5500,109.40,633902,...,34,13,0,109,0,0,0,0,0,365760
12,193533,C1165.0000R,8,2133.04,196.69,97.51,38.26,3730.7326,167.97,853558,...,38,4,0,63,0,0,0,0,0,595200
13,193535,C1332.0000V,3,2154.64,116.43,84.00,33.60,2822.4000,48.01,411244,...,17,11,0,0,3,0,0,0,8,182400
14,193537,C1203.0000R,3,2169.49,173.90,81.03,39.53,3203.1159,50.79,292862,...,35,2,0,72,0,0,0,0,0,149600
15,193594,C1137.0000R,7,2148.84,171.81,90.74,39.30,3566.0820,128.65,750190,...,23,31,0,94,0,0,0,0,1,588000
16,193619,C0121.0000R,5,2134.25,192.58,97.54,39.26,3829.4204,107.62,558992,...,22,5,0,25,0,0,0,0,0,330750
17,193671,C0593.0000R,4,2131.94,193.02,98.28,38.17,3751.3476,47.03,243914,...,14,0,0,5,0,0,0,0,0,148050
18,193686,C1239.0000V,3,2139.48,124.10,63.90,32.33,2065.8870,39.72,318788,...,136,29,0,14,0,0,0,0,17,180600
19,193688,C1349.0000V,3,2116.02,202.47,76.57,38.13,2919.6141,41.72,206626,...,29,17,0,13,0,0,0,0,1,105600
20,193689,C1299.0000R,3,2144.94,161.77,97.67,34.13,3333.4771,46.92,289614,...,24,46,0,46,0,0,0,10,1,103680
21,193692,C0139.0000R,3,2180.91,158.03,89.23,36.70,3274.7410,43.50,276162,...,24,69,0,17,0,0,0,0,1,145200
22,193694,C0529.0000R,5,2185.89,151.22,88.16,37.24,3283.0784,90.77,600586,...,62,64,0,27,1,0,0,0,8,415200
23,193782,C1265.0000R,11,2155.04,132.28,73.79,38.35,2829.8465,187.15,1414754,...,520,3,0,174,0,0,0,0,100,889600
24,193783,C1215.0000R,3,2163.44,188.67,107.80,35.67,3845.2260,60.14,318770,...,37,41,0,32,0,0,0,0,0,107100
25,193784,C1203.0000R,11,2136.07,174.43,92.07,39.18,3607.3026,191.16,1096874,...,56,8,0,142,1,1,1,0,3,794200
26,193852,C1267.0000R,5,2116.76,198.52,91.56,39.16,3585.4896,86.13,434496,...,8,78,0,52,0,0,0,0,0,336000
27,193882,C1268.0000R,8,2139.09,136.54,75.85,37.52,2845.8920,152.83,1120818,...,79,11,0,42,0,0,0,0,11,781200
28,193937,C1172.0000R,3,2137.00,173.13,95.77,36.07,3454.4239,47.54,274688,...,2,9,0,22,0,0,0,0,2,141120
29,193972,C1203.0000R,2,2140.73,173.95,74.00,38.05,2815.7000,44.60,257950,...,45,1,0,27,0,0,0,2,8,138600
30,193973,C1165.0000R,4,2133.13,196.38,105.38,37.65,3967.5570,92.51,471278,...,25,26,0,78,0,0,0,0,1,295200
31,194029,C0132.0000R,4,2144.54,180.00,101.78,37.67,3834.0526,81.26,452828,...,9,9,0,79,1,0,0,34,0,248640
32,194057,C1164.0000R,3,2158.44,169.20,62.87,32.53,2045.1611,66.24,390544,...,23,25,0,2,0,0,0,0,0,192500
33,194113,C0104.0000R,3,2165.69,121.27,76.40,32.50,2483.0000,37.13,304794,...,4,26,0,2,0,0,0,0,0,165000
34,194121,C0516.0000R,6,2149.45,168.88,117.33,33.37,3915.3021,127.02,624892,...,20,80,0,88,0,30,9,2,4,323400

In [42]:
df_producao = df_producao.rename(columns={'Total de Defeitos': 'Defeitos Inspeção Eventual', 'Qtd Empacotado': 'Total Empacotado'})

In [43]:
df_producao['Total Não Empacotado'] = df_producao['Total de Frascos'] - df_producao['Total Empacotado']

In [44]:
# Criando a nova ordem das colunas
nova_ordem = [
    'Ordem de prod', 'Ref. do Artigo', 'Duração da ordem', 'Temperatura (F°)', 
    'Peso médio (g)', 'Comprimento médio (mm)', 'Diâmetro (mm)', 'Área da gota (mm)', 
    'Gotas cortadas (toneladas)', 'Total de Frascos', 'Total Empacotado', 'Total Não Empacotado', 
    'Defeitos Inspeção Eventual', 'Terminação deformada', 'Racho no anel', 'Sujo de óleo', 'Cascão', 
    'Frasco caído na esteira', 'Dupla costura', 'Frio', 'Lascado em produção', 'Dobra', 'Trinca por choque térmico', 
    'Racho na costura', 'Racho na terminação', 'Cava no ombro', 'Ombro mal cheio', 
    'Ombro deformado', 'Martelado', 'Aderido'
]

# Reordenando as colunas do dataframe
df_producao = df_producao[nova_ordem]

In [48]:
df_producao[['Ordem de prod', 'Duração da ordem', 'Total de Frascos', 'Total Empacotado', 'Total Não Empacotado', 'Defeitos Inspeção Eventual']].head()

,Ordem de prod,Duração da ordem,Total de Frascos,Total Empacotado,Total Não Empacotado,Defeitos Inspeção Eventual
0,192970,9,1056298,384300,671998,2148
1,193112,3,266234,207900,58334,584
2,193164,12,1606760,1029000,577760,2661
3,193206,4,433696,181440,252256,1041
4,193207,10,801258,406080,395178,2130

In [46]:
df_producao.to_csv('../dados_empacotados_por_ordem.csv', index=False)